name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        env:
          OAUTH_URI: ${{ secrets.OAUTH_URI }}
          OAUTH_SCOPE: ${{ secrets.OAUTH_SCOPE }}
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          ACKEE_HOST: ${{ secrets.ACKEE_HOST }}
          ACKEE_DOMAIN_ID: ${{ secrets.ACKEE_DOMAIN_ID }}
        run: pnpm run build

      - name: Pre-Deploy
        run: |
          cp dist/index.html dist/404.html
          touch dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
